const STORE = 'papeleria-demo-v1';
const sampleProducts = [
  ['Bastidor Cartón con Tela 25 x 20',30,3,'Arte'],['Cuaderno Profesional Cosido Dibujo Swing',68,4,'Cuadernos'],['Pegamento Blanco 250g Fix-Up',28,1,'Adhesivos'],['Pintura Acrílica Violeta',14,0,'Arte'],['Pintura para Dedos Pelikan 150ml',30,1,'Arte'],['Lápiz Adhesivo',22,12,'Adhesivos'],['Pluma Gel Negra',18,20,'Escritura'],['Caja de Colores 12 piezas',52,8,'Colores'],['Cartulina Escolar Blanca',8,35,'Papel'],['Tijeras Escolares',35,10,'Herramientas']
].map((p,i)=>({id:`sample-${i}`,name:p[0],price:p[1],stock:p[2],category:p[3],image:''}));
let state = JSON.parse(localStorage.getItem(STORE) || 'null') || {products:sampleProducts,cart:[],user:null,orders:[],whatsapp:'523340187767'};
let selectedCategory='Todos';
const $=s=>document.querySelector(s); const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n);
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){renderHeader();renderCatalog();renderCart()}
function renderHeader(){const u=state.user;$('#cartCount').textContent=state.cart.reduce((n,x)=>n+x.qty,0);$('#userStatus').innerHTML=u?`Hola, <strong>${escapeHtml(u.name)}</strong>. Tienes <strong>${u.points} puntos</strong>. Recibes 1 punto por cada $10 en compras confirmadas.`:'Inicia sesión para acumular puntos y consultar tus pedidos.'}
function renderCatalog(){const term=$('#searchInput').value.toLowerCase();const categories=['Todos',...new Set(state.products.map(p=>p.category||'Sin categoría'))];$('#categoryFilters').innerHTML=categories.map(c=>`<button class="filter ${c===selectedCategory?'active':''}" data-category="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join('');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.category;renderCatalog()});const rows=state.products.filter(p=>(selectedCategory==='Todos'||p.category===selectedCategory)&&p.name.toLowerCase().includes(term));$('#productGrid').innerHTML=rows.length?rows.map(p=>`<article class="product"><div class="product-image">${p.image?`<img src="${escapeHtml(p.image.split(',')[0])}" alt="">`:'✏️'}</div><h3>${escapeHtml(p.name)}</h3><p class="category">${escapeHtml(p.category||'Sin categoría')}</p><div class="price">${money(p.price)}</div><p class="stock">${p.stock>0?`${p.stock} disponibles`:'Agotado'}</p><button data-add="${p.id}" ${p.stock<1?'disabled':''}>${p.stock<1?'Agotado':'Agregar'}</button></article>`).join(''):'<p class="empty">No encontramos productos.</p>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add))}
function addCart(id){const p=state.products.find(p=>p.id===id),item=state.cart.find(x=>x.id===id);if(!p||p.stock<1)return;if(item){if(item.qty<p.stock)item.qty++}else state.cart.push({id,qty:1});save();render()}
function renderCart(){const container=$('#cartItems');if(!state.cart.length){container.innerHTML='<p class="empty">Aún no agregas productos.</p>';$('#cartTotal').textContent=money(0);$('#checkoutButton').disabled=true;return}container.innerHTML=state.cart.map(item=>{const p=state.products.find(x=>x.id===item.id);return `<div class="cart-row"><div><strong>${escapeHtml(p.name)}</strong><p>${money(p.price)} c/u</p></div><div class="quantity"><button data-change="${p.id}" data-delta="-1">−</button><span>${item.qty}</span><button data-change="${p.id}" data-delta="1">+</button></div></div>`}).join('');document.querySelectorAll('[data-change]').forEach(b=>b.onclick=()=>changeQty(b.dataset.change,+b.dataset.delta));$('#cartTotal').textContent=money(cartTotal());$('#checkoutButton').disabled=false}
function changeQty(id,delta){const item=state.cart.find(x=>x.id===id),p=state.products.find(x=>x.id===id);item.qty+=delta;if(item.qty<1)state.cart=state.cart.filter(x=>x.id!==id);if(item&&item.qty>p.stock)item.qty=p.stock;save();render()}
function cartTotal(){return state.cart.reduce((n,x)=>{const p=state.products.find(p=>p.id===x.id);return n+p.price*x.qty},0)}
function openPanel(){ $('#cartPanel').classList.add('open');$('#cartPanel').setAttribute('aria-hidden','false');$('#backdrop').classList.add('visible') }function closeAll(){ $('#cartPanel').classList.remove('open');$('#cartPanel').setAttribute('aria-hidden','true');$('#backdrop').classList.remove('visible');document.querySelectorAll('dialog[open]').forEach(d=>d.close())}
function account(){const el=$('#accountContent');if(state.user){el.innerHTML=`<div class="account-hero"><div class="account-mark">✦</div><div><p class="account-eyebrow">Cuenta de cliente</p><h2>Hola, ${escapeHtml(state.user.name)}</h2><p>${escapeHtml(state.user.email)}</p></div></div><div class="points-card"><span>Puntos disponibles</span><strong>${state.user.points}</strong><small>1 punto por cada $10 MXN en compras</small></div><h3>Mis pedidos</h3>${state.orders.filter(o=>o.email===state.user.email).map(o=>`<div class="order-card"><strong>${o.id}</strong><br>${money(o.total)} · ${o.date} ${o.time}<br><small>Pedido enviado para confirmar por WhatsApp</small></div>`).join('')||'<p class="hint">Todavía no tienes pedidos.</p>'}<button class="secondary-button full" id="logout">Cerrar sesión</button>`;$('#accountDialog').showModal();$('#logout').onclick=()=>{state.user=null;save();closeAll();render()};return}el.innerHTML=`<div class="account-hero"><div class="account-mark">✦</div><div><p class="account-eyebrow">Cuenta de cliente</p><h2>Compra más fácil</h2><p>Guarda tus puntos y consulta tus pedidos.</p></div></div><div class="account-tabs" role="tablist"><button class="active" id="showLogin" type="button">Iniciar sesión</button><button id="showRegister" type="button">Crear cuenta</button></div><form id="authForm"></form><p class="local-note">Esta demostración guarda la cuenta sólo en este navegador.</p>`;$('#accountDialog').showModal();let registering=false;const draw=()=>{$('#authForm').innerHTML=`${registering?'<label>Nombre completo<input name="name" autocomplete="name" required maxlength="60" placeholder="Tu nombre"></label>':''}<label>Correo electrónico<input type="email" name="email" autocomplete="email" required placeholder="nombre@correo.com"></label><label>Contraseña<div class="password-field"><input type="password" name="password" autocomplete="current-password" minlength="6" required placeholder="Mínimo 6 caracteres"><button type="button" class="password-toggle" aria-label="Mostrar contraseña">Mostrar</button></div></label><button class="primary-button full">${registering?'Crear mi cuenta':'Entrar a mi cuenta'}</button>`;$('.password-toggle').onclick=()=>{const input=$('#authForm input[name="password"]'),button=$('.password-toggle'),show=input.type==='password';input.type=show?'text':'password';button.textContent=show?'Ocultar':'Mostrar';button.setAttribute('aria-label',show?'Ocultar contraseña':'Mostrar contraseña')};$('#authForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.user={name:f.get('name')||f.get('email').split('@')[0],email:f.get('email'),points:state.user?.points||0};save();closeAll();render()}};$('#showLogin').onclick=()=>{registering=false;$('#showLogin').classList.add('active');$('#showRegister').classList.remove('active');draw()};$('#showRegister').onclick=()=>{registering=true;$('#showRegister').classList.add('active');$('#showLogin').classList.remove('active');draw()};draw()}
function checkout(){if(!state.cart.length)return;if(!state.user){account();return}$('#checkoutForm').elements.name.value=state.user.name;$('#checkoutForm').elements.phone.value='';$('#checkoutForm').elements.date.min=new Date().toISOString().slice(0,10);$('#checkoutDialog').showModal()}
function finishOrder(e){e.preventDefault();const f=new FormData(e.target), total=cartTotal();const order={id:`PED-${Date.now().toString().slice(-6)}`,email:state.user.email,name:f.get('name'),phone:f.get('phone'),date:f.get('date'),time:f.get('time'),notes:f.get('notes'),items:state.cart.map(x=>({...x,product:state.products.find(p=>p.id===x.id)})),total};state.orders.unshift(order);state.user.points+=Math.floor(total/10);state.cart=[];save();closeAll();render();const details=order.items.map(i=>`• ${i.qty} x ${i.product.name} (${money(i.product.price*i.qty)})`).join('\n');const message=`Hola, tengo un pedido para recoger en la papelería.%0A%0A*${order.id}*%0ACliente: ${order.name}%0ATeléfono: ${order.phone}%0AFecha y hora sugerida: ${order.date} ${order.time}%0A%0A${details}%0A%0A*Total: ${money(total)}*%0APago en efectivo al recoger.${order.notes?`%0ANota: ${order.notes}`:''}`;$('#orderContent').innerHTML=`<h2>Pedido registrado</h2><p>Acumulaste <strong>${Math.floor(total/10)} puntos</strong>. Abre WhatsApp para enviar el pedido y acordar la hora de recogida.</p><a class="primary-button full" target="_blank" rel="noopener" href="https://wa.me/${state.whatsapp}?text=${encodeURIComponent(decodeURIComponent(message))}">Abrir WhatsApp</a><p class="hint">Pedido ${order.id} · ${money(total)}</p>`;$('#orderDialog').showModal()}
function parseCsv(text){const out=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))out.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);out.push(row)}const headers=out.shift().map(h=>h.replace(/^\uFEFF/,'').trim());return out.map(r=>Object.fromEntries(headers.map((h,i)=>[h,(r[i]||'').trim()])))}
$('#csvInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const records=parseCsv(reader.result);const products=records.map((r,i)=>({id:`import-${Date.now()}-${i}`,name:r['Nombre']||r.nombre||r.Name||'',price:Number((r['Precio normal']||r.precio||r.Precio||r.price||'').replace(/[^0-9.]/g,'')),stock:Number(r['Inventario']||r.inventario||r.stock||0),category:r['Categorías']||r.categoria||r.Categoría||r.category||'Sin categoría',image:r['Imágenes']||r.imagen||r.image||''})).filter(p=>p.name&&Number.isFinite(p.price));if(!products.length)throw Error();state.products=products;state.cart=[];save();selectedCategory='Todos';render();$('#importResult').textContent=`Importación terminada: ${products.length} productos listos en el catálogo.`}catch{$('#importResult').textContent='No pudimos leer ese archivo. Revisa que sea un CSV con nombre y precio.'}};reader.readAsText(file,'UTF-8')};
$('#restoreButton').onclick=()=>{state.products=sampleProducts;state.cart=[];save();render();$('#importResult').textContent='Se restauró el catálogo de muestra.'};$('#searchInput').oninput=renderCatalog;$('#cartButton').onclick=openPanel;$('#accountButton').onclick=account;$('#checkoutButton').onclick=checkout;$('#checkoutForm').onsubmit=finishOrder;$('#backdrop').onclick=closeAll;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeAll);render();
