const STORE = 'papeleria-demo-v1';
const sampleProducts = [
  ['Bastidor Cartón con Tela 25 x 20',30,3,'Arte'],['Cuaderno Profesional Cosido Dibujo Swing',68,4,'Cuadernos'],['Pegamento Blanco 250g Fix-Up',28,1,'Adhesivos'],['Pintura Acrílica Violeta',14,0,'Arte'],['Pintura para Dedos Pelikan 150ml',30,1,'Arte'],['Lápiz Adhesivo',22,12,'Adhesivos'],['Pluma Gel Negra',18,20,'Escritura'],['Caja de Colores 12 piezas',52,8,'Colores'],['Cartulina Escolar Blanca',8,35,'Papel'],['Tijeras Escolares',35,10,'Herramientas']
].map((p,i)=>({id:`sample-${i}`,name:p[0],price:p[1],stock:p[2],category:p[3],image:''}));
let state = JSON.parse(localStorage.getItem(STORE) || 'null') || {products:sampleProducts,cart:[],orders:[]};
const WHATSAPP_NUMBER = '523340187767';
let selectedCategory='Todos', selectedSort='name';
const $=s=>document.querySelector(s); const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n);
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
const cloud=window.supabase&&window.CYBERTIME_SUPABASE?window.supabase.createClient(window.CYBERTIME_SUPABASE.url,window.CYBERTIME_SUPABASE.publishableKey):null;
async function loadCloudCatalog(){if(!cloud)return;let allData=[];let page=0;const pageSize=1000;while(true){const {data,error}=await cloud.from('products').select('id,sku,name,category,price,stock,minimum_stock,image_url').eq('is_active',true).order('name').range(page*pageSize,(page+1)*pageSize-1);if(error){console.warn('No se pudo actualizar el catálogo',error.message);return}if(!data||!data.length)break;allData.push(...data);if(data.length<pageSize)break;page++}state.products=allData.map(p=>({id:String(p.id),sku:p.sku||'',name:p.name,category:p.category||'Sin categoría',price:Number(p.price)||0,stock:Number(p.stock)||0,minimum_stock:Number(p.minimum_stock)||0,image:p.image_url||''}));state.cart=state.cart.filter(item=>state.products.some(p=>p.id===item.id));save();render()}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){renderHeader();renderCatalog();renderCart()}
function renderHeader(){$('#cartCount').textContent=state.cart.reduce((n,x)=>n+x.qty,0);}
function categoryFor(product){const existing=String(product.category||'').trim();if(existing&&!/^(uncategorized|sin categor[ií]a)$/i.test(existing))return existing.split('>').pop().trim();const n=String(product.name||'').toLowerCase();if(/cuaderno|libreta|agenda|block|notebook/.test(n))return 'Cuadernos y libretas';if(/pluma|lapiz|lápiz|marcador|bol[ií]grafo|boligrafo|resaltador|crayon/.test(n))return 'Escritura';if(/pintura|acuarela|pincel|bastidor|lienzo|plastilina|color/.test(n))return 'Arte y colores';if(/pegamento|cinta|silic[oó]n|adhesivo|grapa/.test(n))return 'Adhesivos';if(/cartulina|papel|hoja|opalin|foamy|mica/.test(n))return 'Papel y cartulina';if(/tijera|regla|comp[aá]s|sacapuntas|corrector|cutter/.test(n))return 'Herramientas';return 'Papelería';}
function renderCatalog(){let categorized=false;state.products.forEach(p=>{const c=categoryFor(p);if(p.category!==c){p.category=c;categorized=true}});if(categorized)save();const term=$('#searchInput').value.trim().toLowerCase(),categories=[...new Set(state.products.map(p=>p.category))].sort((a,b)=>a.localeCompare(b,'es'));if(selectedCategory!=='Todos'&&!categories.includes(selectedCategory))selectedCategory='Todos';$('#categoryFilters').innerHTML=['Todos',...categories].map(c=>{const count=c==='Todos'?state.products.length:state.products.filter(p=>p.category===c).length;return `<button class="filter ${c===selectedCategory?'active':''}" data-category="${escapeHtml(c)}">${escapeHtml(c)} <span>${count}</span></button>`}).join('');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.category;renderCatalog()});let rows=state.products.filter(p=>(selectedCategory==='Todos'||p.category===selectedCategory)&&`${p.name} ${p.category} ${p.sku||''}`.toLowerCase().includes(term));rows.sort((a,b)=>selectedSort==='price-asc'?a.price-b.price:selectedSort==='price-desc'?b.price-a.price:selectedSort==='stock'?b.stock-a.stock:a.name.localeCompare(b.name,'es'));$('#catalogSummary').textContent=`${rows.length} producto${rows.length===1?'':'s'} ${selectedCategory==='Todos'?'disponibles en el catálogo':`en ${selectedCategory}`}`;$('#productGrid').innerHTML=rows.length?rows.map(p=>`<article class="product"><div class="product-image">${p.image?`<img src="${escapeHtml(p.image.split(',')[0])}" alt="">`:'✏️'}</div><p class="category">${escapeHtml(p.category)}</p><h3>${escapeHtml(p.name)}</h3><div class="price">${money(p.price)}</div><p class="stock ${p.stock<1?'sold-out':''}">${p.stock>0?`${p.stock} disponibles`:'Agotado'}</p><button data-add="${p.id}" ${p.stock<1?'disabled':''}>${p.stock<1?'Agotado':'Agregar al carrito'}</button></article>`).join(''):'<p class="empty">No encontramos productos con esa búsqueda. Prueba otra categoría o término.</p>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addCart(b.dataset.add))}
function addCart(id){const p=state.products.find(p=>p.id===id),item=state.cart.find(x=>x.id===id);if(!p||p.stock<1)return;if(item){if(item.qty<p.stock)item.qty++}else state.cart.push({id,qty:1});save();render()}
function renderCart(){const container=$('#cartItems');if(!state.cart.length){container.innerHTML='<p class="empty">Aún no agregas productos.</p>';$('#cartTotal').textContent=money(0);$('#checkoutButton').disabled=true;return}container.innerHTML=state.cart.map(item=>{const p=state.products.find(x=>x.id===item.id);return `<div class="cart-row"><div><strong>${escapeHtml(p.name)}</strong><p>${money(p.price)} c/u</p></div><div class="quantity"><button data-change="${p.id}" data-delta="-1">−</button><span>${item.qty}</span><button data-change="${p.id}" data-delta="1">+</button></div></div>`}).join('');document.querySelectorAll('[data-change]').forEach(b=>b.onclick=()=>changeQty(b.dataset.change,+b.dataset.delta));$('#cartTotal').textContent=money(cartTotal());$('#checkoutButton').disabled=false}
function changeQty(id,delta){const item=state.cart.find(x=>x.id===id),p=state.products.find(x=>x.id===id);item.qty+=delta;if(item.qty<1)state.cart=state.cart.filter(x=>x.id!==id);if(item&&item.qty>p.stock)item.qty=p.stock;save();render()}
function cartTotal(){return state.cart.reduce((n,x)=>{const p=state.products.find(p=>p.id===x.id);return n+p.price*x.qty},0)}
function openPanel(){ $('#cartPanel').classList.add('open');$('#cartPanel').setAttribute('aria-hidden','false');$('#backdrop').classList.add('visible') }function closeAll(){ $('#cartPanel').classList.remove('open');$('#cartPanel').setAttribute('aria-hidden','true');$('#backdrop').classList.remove('visible');document.querySelectorAll('dialog[open]').forEach(d=>d.close())}
function checkout(){if(!state.cart.length)return;$('#checkoutDialog').showModal()}
async function finishOrder(e){
  e.preventDefault();const f=new FormData(e.target), total=cartTotal();
  const phone = f.get('phone'), name = f.get('name'), notes = f.get('notes');
  const earnedPoints = Math.floor(total/10);
  let totalPoints = earnedPoints;
  if(cloud){
    const { data } = await cloud.from('customers').select('points').eq('phone', phone).maybeSingle();
    totalPoints = (data?.points || 0) + earnedPoints;
    await cloud.from('customers').upsert({ phone, name, points: totalPoints });
  }
  const order={id:`PED-${Date.now().toString().slice(-6)}`,name,phone,notes,items:state.cart.map(x=>({...x,product:state.products.find(p=>p.id===x.id)})),total};
  state.orders.unshift(order);
  state.cart=[];save();closeAll();render();
  const details=order.items.map(i=>`• ${i.qty} x ${i.product.name} (${money(i.product.price*i.qty)})`).join('\n');
  const message=`Hola, tengo un pedido para recoger en la papelería.%0A%0A*${order.id}*%0ACliente: ${order.name}%0ATeléfono: ${order.phone}%0A%0A${details}%0A%0A*Total: ${money(total)}*%0APago en efectivo al recoger.${order.notes?`%0ANota: ${order.notes}`:''}%0A%0ASumé ${earnedPoints} puntos con este pedido y llevo ${totalPoints} puntos.`;
  $('#orderContent').innerHTML=`<h2>Pedido registrado</h2><p>Acumulaste <strong>${earnedPoints} puntos</strong> y ahora tienes <strong>${totalPoints}</strong>. Abre WhatsApp para enviar el pedido y acordar la hora de recogida.</p><a class="primary-button full" target="_blank" rel="noopener" href="https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}">Abrir WhatsApp</a><p class="hint">Pedido ${order.id} · ${money(total)}</p>`;
  $('#orderDialog').showModal()
}
function parseCsv(text){const out=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))out.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);out.push(row)}const headers=out.shift().map(h=>h.replace(/^\uFEFF/,'').trim());return out.map(r=>Object.fromEntries(headers.map((h,i)=>[h,(r[i]||'').trim()])))}
$('#csvInput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const records=parseCsv(reader.result);const products=records.map((r,i)=>({id:`import-${Date.now()}-${i}`,name:r['Nombre']||r.nombre||r.Name||'',price:Number((r['Precio normal']||r.precio||r.Precio||r.price||'').replace(/[^0-9.]/g,'')),stock:Number(r['Inventario']||r.inventario||r.stock||0),category:r['Categorías']||r.categoria||r.Categoría||r.category||'Sin categoría',image:r['Imágenes']||r.imagen||r.image||''})).filter(p=>p.name&&Number.isFinite(p.price));if(!products.length)throw Error();state.products=products;state.cart=[];save();selectedCategory='Todos';render();$('#importResult').textContent=`Importación terminada: ${products.length} productos listos en el catálogo.`}catch{$('#importResult').textContent='No pudimos leer ese archivo. Revisa que sea un CSV con nombre y precio.'}};reader.readAsText(file,'UTF-8')};
$('#restoreButton').onclick=()=>{state.products=sampleProducts;state.cart=[];save();render();$('#importResult').textContent='Se restauró el catálogo de muestra.'};$('#searchInput').oninput=renderCatalog;$('#cartButton').onclick=openPanel;$('#checkoutButton').onclick=checkout;$('#checkoutForm').onsubmit=finishOrder;$('#backdrop').onclick=closeAll;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeAll);render();
